# Generated by Django 4.2.5 on 2023-09-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adultform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=200)),
                ('Hobbies', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Kidsform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=200)),
                ('Hobbies', models.CharField(max_length=30)),
                ('DOB', models.DateField(max_length=8)),
            ],
        ),
    ]
